# Generated by Django 6.0 on 2025-12-13 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва обладнання')),
                ('image', models.ImageField(blank=True, null=True, upload_to='assets/', verbose_name='Фото')),
                ('inventory_number', models.CharField(max_length=50, unique=True, verbose_name='Інвентарний номер')),
                ('specs', models.TextField(blank=True, verbose_name='Характеристики')),
                ('location', models.CharField(max_length=100, verbose_name='Розташування')),
            ],
            options={
                'verbose_name': 'Актив',
                'verbose_name_plural': 'Активи',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Тема')),
                ('description', models.TextField(verbose_name='Детальний опис проблеми')),
                ('status', models.CharField(choices=[('new', 'Нова'), ('in_progress', 'В роботі'), ('done', 'Виконано'), ('closed', 'Закрито')], default='new', max_length=20, verbose_name='Статус')),
                ('priority', models.CharField(choices=[('low', 'Низька'), ('medium', 'Середня'), ('high', 'Висока'), ('critical', 'Критична')], default='medium', max_length=20, verbose_name='Терміновість')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.asset', verbose_name='Обладнання')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Виконавець')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Повідомлення')),
                ('is_internal', models.BooleanField(default=False, verbose_name='Приватна нотатка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.ticket')),
            ],
        ),
    ]
