# Generated by Django 6.0 on 2025-12-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_ticket_asset_remove_ticket_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('Low', 'Низька (Можу почекати)'), ('Medium', 'Середня'), ('High', 'Висока (Терміново)')], default='Low', max_length=20, verbose_name='Терміновість'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Тема'),
        ),
    ]
