# Generated by Django 6.0 on 2025-12-13 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ticket_assigned_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='Тип (напр. Ноутбук)')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('status', models.CharField(choices=[('Вжитку', 'Вжитку'), ('На складі', 'На складі'), ('Списано', 'Списано'), ('В ремонті', 'В ремонті')], default='Вжитку', max_length=50, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Обладнання',
                'verbose_name_plural': 'Інвентаризація',
            },
        ),
    ]
