# Generated by Django 6.0 on 2025-12-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_inventoryitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_internal',
            field=models.BooleanField(default=False, verbose_name='Тільки для фахівців'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='Текст коментаря'),
        ),
    ]
